### PR TITLE
Hotfix/anders nord interview image

### PR DESCRIPTION
**Pull request by mgcth**
**Description**

Hack for github pages.

### CODE REVIEW

**Comment by mgcth** [comment]
Damn, this won't work either. So, I'll have to solve the core problem, for now let's try an even bigger hack.

**Comment by mgcth** [comment]
@docNord, we can go with this. It isn't a hack, and should work fine in future uses too.

**Comment by mgcth** [comment]
While I have you on the line @docNord, can you approve this so we finally render you on the page... Took a while.

**Review by docNord — APPROVED** [review]

**Comment by docNord** [comment]
Well worth the wait though! 😊 Sorry, Monday nights are vacuuming nights in the Nord residence...

**Pull request merged**
